INSERT INTO crust (name, price) VALUES ('Small Thin', 8);
INSERT INTO crust (name, price) VALUES ('Small Deep Dish', 8);
INSERT INTO crust (name, price) VALUES ('Small Original', 8);
INSERT INTO crust (name, price) VALUES ('Medium Thin', 10);
INSERT INTO crust (name, price) VALUES ('Medium Deep Dish', 10);
INSERT INTO crust (name, price) VALUES ('Medium Original', 10);
INSERT INTO crust (name, price) VALUES ('Large Thin', 12);
INSERT INTO crust (name, price) VALUES ('Large Deep Dish', 12);
INSERT INTO crust (name, price) VALUES ('Large Original', 12);
INSERT INTO crust (name, price) VALUES ('Surprise Crust', 14);
