INSERT INTO specialty_pizza (description, price) VALUES ('Small Meaty', 10);
INSERT INTO specialty_pizza (description, price) VALUES ('Small Veggie', 10);
INSERT INTO specialty_pizza (description, price) VALUES ('Small Mixey', 10);
INSERT INTO specialty_pizza (description, price) VALUES ('Medium Meaty', 12);
INSERT INTO specialty_pizza (description, price) VALUES ('Medium Veggie', 12);
INSERT INTO specialty_pizza (description, price) VALUES ('Medium Mixey', 12);
INSERT INTO specialty_pizza (description, price) VALUES ('Large Meaty', 14);
INSERT INTO specialty_pizza (description, price) VALUES ('Large Veggie', 14);
INSERT INTO specialty_pizza (description, price) VALUES ('Large Mixey', 14);
INSERT INTO specialty_pizza (description, price) VALUES ('Its a secret', 16);
